name: PPOAgent
params:
  seed: ${...seed}

  model:
    actor_mlp: [256, 256]
    critic_mlp: [256, 256]

  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    device: ${....rl_device}
    save_frequency: 10

    normalize_obs: True
    normalize_value: False
    normalize_advantage: True

    horizon_length: 2048
    max_epochs: ${resolve_default:200,${....max_iterations}}
    mini_epochs: 6
    minibatch_size: 512

    tau: 0.9
    gamma: 0.9
    e_clip: 0.2
    clip_value: False

    learning_rate: 1e-3
    critic_loss_coef: 1
    bounds_loss_coef: 10
    grad_penalty_coef: 0
